# Generated by Django 3.2.4 on 2021-12-18 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productdetails',
            new_name='Blogdetails',
        ),
    ]
