# Generated by Django 3.2.4 on 2021-12-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_rename_productdetails_blogdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetails',
            name='heading1',
            field=models.CharField(default='', max_length=50000),
        ),
        migrations.AlterField(
            model_name='blogdetails',
            name='heading2',
            field=models.CharField(default='', max_length=50000),
        ),
    ]
