# Generated by Django 3.2.4 on 2021-12-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20211218_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetails',
            name='dheading0',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='blogdetails',
            name='dheading1',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='blogdetails',
            name='dheading2',
            field=models.CharField(default='', max_length=50000),
        ),
        migrations.AlterField(
            model_name='blogdetails',
            name='heading0',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='blogdetails',
            name='heading2',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='blogdetails',
            name='product_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
