# Generated by Django 3.2.4 on 2021-12-18 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20211218_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogdetails',
            old_name='product_date',
            new_name='Blog_date',
        ),
    ]
