# Generated by Django 3.2.4 on 2021-10-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdetails",
            name="Price",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productdetails",
            name="Sub_category",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="productdetails",
            name="category",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="productdetails",
            name="image",
            field=models.ImageField(default="", upload_to="Shops/images"),
        ),
    ]
