# Generated by Django 3.2.4 on 2021-11-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_auto_20211030_1859"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("C_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("Phoneno", models.CharField(max_length=10)),
                ("desc", models.CharField(max_length=500)),
            ],
        ),
    ]
