# Generated by Django 3.2.4 on 2021-11-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                ("O_id", models.AutoField(primary_key=True, serialize=False)),
                ("item_Json", models.CharField(max_length=100)),
                ("Name", models.CharField(max_length=50)),
                ("Email_id", models.EmailField(max_length=100)),
                ("Address", models.CharField(max_length=111)),
                ("City", models.CharField(max_length=111)),
                ("State", models.CharField(max_length=100)),
                ("Zip_code", models.CharField(max_length=100)),
                ("Phone_number", models.CharField(default="", max_length=100)),
            ],
        ),
    ]
