# Generated by Django 3.2.4 on 2021-11-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_orders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="item_Json",
            field=models.CharField(max_length=5000),
        ),
    ]
