# Generated by Django 3.2.4 on 2021-12-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_solution"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderUpdate",
            fields=[
                ("update_id", models.AutoField(primary_key=True, serialize=False)),
                ("order_id", models.IntegerField(default="")),
                ("update_desc", models.CharField(max_length=10000)),
                ("timeStamp", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
