# Generated by Django 3.2.4 on 2021-12-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_orderupdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderupdate",
            name="Phone_number",
            field=models.CharField(default="", max_length=100),
        ),
    ]
