# Generated by Django 3.2.4 on 2021-12-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_productdetails_quantities'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Amount',
            field=models.IntegerField(default=0),
        ),
    ]
